import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lavender Interiors — design ideas for our apartment",
  description:
    "Pick a room in our apartment, describe a look you like, and see three interior design ideas — generated by AI from our floor plan.",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#fdfaf3",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="relative min-h-screen">
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
